config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :templets do 
    resources :flowpath
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :templet


end

app/models/flowpath.rb
class Flowpath < ApplicationRecord
  belongs_to :templet
  belongs_to :user
end

app/models/templet.rb
class Templet < ApplicationRecord
  has_many :flowpaths, inverse_of: :templet
  has_many :users,through: :flowpaths
  accepts_nested_attributes_for :flowpaths 

  has_many :events
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :flowpaths
  has_many :templets, through: :flowpaths




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:content, :status, :templet_id, :user_id)
    end
end

app/controllers/flowpath_controller.rb
class FlowpathController < ApplicationController
 def new
 end

end

app/controllers/templets_controller.rb
class TempletsController < ApplicationController
  before_action :set_templet, only: [:show, :edit, :update, :destroy]

  # GET /templets
  # GET /templets.json
  def index
    @templets = Templet.all
  end

  # GET /templets/1
  # GET /templets/1.json
  def show
  end

  # GET /templets/new
  def new
    @templet = Templet.new
    @templet.flowpaths.build
  end

  # GET /templets/1/edit
  def edit
  end

  # POST /templets
  # POST /templets.json
  def create
    @templet = Templet.new(templet_params)
    @templet["stutus"] = 1
    respond_to do |format|
      if @templet.save
        format.html { redirect_to @templet, notice: 'Templet was successfully created.' }
        format.json { render :show, status: :created, location: @templet }
      else
        format.html {  render :new }
        format.json { render json: @templet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /templets/1
  # PATCH/PUT /templets/1.json
  def update
    respond_to do |format|
      if @templet.update(templet_params)
        format.html { redirect_to @templet, notice: 'Templet was successfully updated.' }
        format.json { render :show, status: :ok, location: @templet }
      else
        format.html { render :edit }
        format.json { render json: @templet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /templets/1
  # DELETE /templets/1.json
  def destroy
    respond_to do |format|
      if @templet.update(stutus: 2)
        format.html { redirect_to templets_url, notice: 'Templet was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :edit }
        format.json { render json: @templet.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_templet
      @templet = Templet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def templet_params
      params.require(:templet).permit(:typename, :stutus, flowpaths_attributes: [:user_id,:sequence])
    end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/flowpath_helper.rb
module FlowpathHelper
end

app/helpers/templets_helper.rb
module TempletsHelper
end

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :content %>
    <%= f.input :status %>
    <%= f.input :templet_id %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Status</th>
      <th>Templet</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.content %></td>
        <td><%= event.status %></td>
        <td><%= event.templet_id %></td>
        <td><%= event.user_id %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event', new_event_path %>

app/views/events/new.html.erb
<h1>New Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @event.content %>
</p>

<p>
  <strong>Status:</strong>
  <%= @event.status %>
</p>

<p>
  <strong>Templet:</strong>
  <%= @event.templet_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @event.user_id %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>XdstarOa</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/templets/_form.html.erb
<%= simple_form_for templet do |f| %>
  <% if templet.errors.any? %>
    <div  id="error_explanation">
      <h2> <%= pluralize(templet.errors.count, "error") %> prohibited this templet from being saved:</h2>

      <ul>
      <% templet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.input :typename%>
  <%= f.button :submit%>
    
<% end %>

app/views/templets/edit.html.erb
<h1>Editing Templet</h1>

<%= render 'form', templet: @templet %>

<%= link_to 'Show', @templet %> |
<%= link_to 'Back', templets_path %>

app/views/templets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Templets</h1>

<table>
  <thead>
    <tr>
      <th>Typename</th>
      <th>Stutus</th>
      <th>create time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @templets.each do |templet| %>
      <tr>
        <td><%= templet.typename %></td>
        <td><%= templet.stutus %></td>
        <td><%= templet.created_at%></td>
        <td><%= link_to 'Show', templet %></td>
        <td><%= link_to 'Edit', edit_templet_path(templet) %></td>
        <td><%= link_to 'Destroy', templet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Templet', new_templet_path %>

app/views/templets/new.html.erb
<h1>New Templet</h1>
<%= simple_form_for @templet do |f| %>
  <% if @templet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@templet.errors.count, "error") %> prohibited this templet from being saved:</h2>

      <ul>
      <% @templet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="actions">
        <input type="submit" name="commit" value="Create Templet" data-disable-with="Create Templet" />
          </div>

            <div class="field">
                  <label for="templet_typename">Typename</label>
                      <input type="text" name="templet[typename]" id="templet_typename" />
                        </div>
                          
                              <label for="templet_flowpaths_attributes_0_user_id">User</label>
                              </br>
                                   




  <input name="" type="button" value="添加人员" onClick="AddInput()" /> 
  <input name="" type="button" value="删减人员" onClick="SubInput()" /> 

</br>

<script type="text/javascript">

var i = 1;
function AddInput(){
  TemO=document.getElementById("new_templet");  
  var user_strname =  "templet[flowpaths_attributes][" + i + "][user_id]" ;
  var user_strid = "templet_flowpaths_attributes_"+i+"_user_id"
    var newInput1 = document.createElement("input"); 
  newInput1.type = "input";
  newInput1.name = user_strname;
  newInput1.id = user_strid;

  var sequence_strname =  "templet[flowpaths_attributes][" + i + "][sequence]" ;
  var sequence_strid = "templet_flowpaths_attributes_"+i+"_sequence";
  var newInput2 = document.createElement("input"); 
  newInput2.type = "input";
  newInput2.name = sequence_strname;
  newInput2.id = sequence_strid;
  newInput2.value = i;
  newInput2.style.display='none';

  TemO.appendChild(newInput1);
  TemO.appendChild(newInput2); 



  var newline= document.createElement("br");  
          TemO.appendChild(newline);  

          i++; 
}
function SubInput(){
  if(i>1){
      i--
      var user_strid ="templet_flowpaths_attributes_"+i+"_user_id";
      var sequence_strid = "templet_flowpaths_attributes_"+i+"_sequence"
      var Temo = document.getElementById("new_templet");
      var newInput1 = document.getElementById(user_strid);
      var newInput2 = document.getElementById(sequence_strid);
      TemO.removeChild(newInput1); 
      TemO.removeChild(newInput2); 

  }else
  {alert("NO ONE")}
}
 </script>

<% end %>
<%= link_to 'Back', templets_path %>

app/views/templets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Typename:</strong>
  <%= @templet.typename %>
</p>

<p>
  <strong>Stutus:</str ong>
  <%= @templet.stutus %>
</p>

<p>
<strong>flowpath:</strong>
</br>
<% @templet.flowpaths.each do |flowpath|%>
  <tr>
    <td><%= flowpath.user_id%></td>
    <td><%= flowpath.sequence%>
  </tr>
  </br>
<%end%> 
</p>
<%= link_to 'Edit', edit_templet_path(@templet) %> |
<%= link_to 'Back', templets_path %>